spring:
  application:
    name: "spring-tracing-test-1"
  sleuth:
    propagation:
      type: b3
    opentracing:
      enabled: true
  zipkin:
    base-url: "http://10.43.202.158:9411"
#    base-url: "http://localhost:9411"
server:
  port: 7002