spring:
  application:
    name: "spring-tracing-test-2"
  sleuth:
    otel:
      exporter:
        jaeger:
          endpoint: "http://localhost:14268/api/traces"
          timeout: 3000

server:
  port: 7001